sudo: false #use container based infrastructure
language: node_js
node_js:
  - "0.12"

addons:
  apt:
    sources:
      - libnotify-bin

install:
  - travis_retry npm install -g gulp
  - travis_retry npm install

script:
  - gulp test

after_script:
  - gulp coveralls
